version: '3'

services:
  
  wordpress:
    image: wordpress:php7.4-apache
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=fuerzastudio
      - WORDPRESS_DB_NAME=wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      #- certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email mgoncalves@golesuite.com --agree-tos --no-eff-email --staging -d wp.desafio.com

volumes:
  #certbot-etc:
  wordpress:

networks:
  app-network:
    driver: bridge
